# Generated by Django 2.0.4 on 2018-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagemProduto',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
