# Generated by Django 2.0.4 on 2018-04-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20180422_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagemProduto',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
